1. Simulate any random rectangular matrix A.

In [1]:
import numpy as np
from random import *
m = int(input("Digite el Número de Filas (m): "))
n = int(input("Digite el Número de Columnas (n): "))
A = [[randint(1, 10) for j in range(n)] for i in range(m)]
for row in A:
    print(row)

[5, 7, 7, 9, 6]
[7, 8, 8, 5, 10]
[7, 1, 7, 5, 3]
[2, 2, 8, 3, 3]
[7, 10, 10, 4, 7]


What is the rank and trace of A?

**np.linalg.matrix_rank =** Recibe una matrix y retorna el numero de columnas linealmente independientes.

In [2]:
rank = np.linalg.matrix_rank(A)
print(f"Rango de la matrix A: {rank}")

Rango de la matrix A: 5


What is the determinant of A?

In [3]:
from numpy import linalg as LA
d = int(input("Debido a que solo se puede calcular para matrices cuadradas ingrese el # Filas y Columnas "))
A = [[randint(1, 10) for j in range(d)] for i in range(d)]
for row in A:
    print(row)
Determinante = np.linalg.det(A) 
print(f"\nLa Determinante de la matrix anterior es {Determinante}")

[10, 7, 3, 7, 1]
[4, 2, 1, 4, 5]
[1, 9, 7, 8, 9]
[9, 9, 9, 8, 9]
[2, 7, 1, 10, 2]

La Determinante de la matrix anterior es -4346.000000000007


2. Can you invert A? How?

In [4]:
from numpy import linalg as LA
print("Impresión de la matrix del punto anterior 'A'")
for row in A:
    print(row)
#Inversa= np.linalg.inv(m)
Inversa = LA.inv(A)
print(f"\nLa Inversa de la matrix anterior es {Inversa}")

Impresión de la matrix del punto anterior 'A'
[10, 7, 3, 7, 1]
[4, 2, 1, 4, 5]
[1, 9, 7, 8, 9]
[9, 9, 9, 8, 9]
[2, 7, 1, 10, 2]

La Inversa de la matrix anterior es [[ 0.09295904  0.07777266 -0.03014266 -0.00897377 -0.06488725]
 [ 0.51817763  0.06718822  0.57455131 -0.58467556 -0.38150023]
 [-0.37183617 -0.31109066 -0.37942936  0.53589508  0.25954901]
 [-0.36033134 -0.07869305 -0.39553613  0.39369535  0.38518178]
 [ 0.08099402  0.23607915  0.18660838 -0.18108606 -0.15554533]]


How are eigenvalues and eigenvectors of A’A and AA’ related? What interesting differences can you notice between both?

**https://sites.cs.ucsb.edu/~mturk/Papers/jcn.pdf**

In [5]:
print("Impresión de la matrix del punto anterior 'A'")
for row in A:
    print(row)
print("***************")
Eigenvalues , Eigenvectors = np.linalg.eig(A)
print("Eigenvalues ", Eigenvalues,"\n")
print("Eigenvectors ", Eigenvectors)

Impresión de la matrix del punto anterior 'A'
[10, 7, 3, 7, 1]
[4, 2, 1, 4, 5]
[1, 9, 7, 8, 9]
[9, 9, 9, 8, 9]
[2, 7, 1, 10, 2]
***************
Eigenvalues  [ 2.90417531e+01+0.j          6.29816386e+00+0.j
 -6.28254281e+00+0.j         -2.86870977e-02+1.94451583j
 -2.86870977e-02-1.94451583j] 

Eigenvectors  [[ 0.41792645+0.j          0.61549331+0.j          0.3055437 +0.j
   0.01399904-0.08951733j  0.01399904+0.08951733j]
 [ 0.23857984+0.j          0.18868516+0.j         -0.4100941 +0.j
  -0.58783962+0.j         -0.58783962-0.j        ]
 [ 0.48989652+0.j         -0.73993851+0.j         -0.01807848+0.j
   0.38629406+0.43432944j  0.38629406-0.43432944j]
 [ 0.63875821+0.j         -0.19310144+0.j         -0.40139344+0.j
   0.45800332-0.02163886j  0.45800332+0.02163886j]
 [ 0.34699638+0.j         -0.02772584+0.j          0.75961988+0.j
  -0.21635217-0.22655363j -0.21635217+0.22655363j]]


---
"Diferencias entre Eigenvalues y Eigenvectors"
---

| Característica | Eigenvalues (Valores propios) | Eigenvectors (Vectores propios) |
|---|---|---|
| **Tipo** | Escalar | Vector |
| **Representación** | Cantidad de escala | Dirección de escala |
| **Cálculo** | Ecuación característica: det(A - λI) = 0 | Sistema de ecuaciones: (A - λI)v = 0 |
| **Cantidad** | Igual a la dimensión de la matriz | Uno por cada eigenvalue |
| **Valores** | Reales, complejos, positivos, negativos o cero | Linealmente independientes entre sí |

**Resumen:**

* Los eigenvalues son escalares, mientras que los eigenvectors son vectores.
* Los eigenvalues representan la cantidad por la que se escala un vector, mientras que los eigenvectors representan la dirección en la que se escala.
* Los eigenvalues se encuentran resolviendo la ecuación característica, mientras que los eigenvectors se encuentran resolviendo un sistema de ecuaciones.